package repository

type ScryCard struct {
	Object        string `json:"object"`
	ID            string `json:"id"`
	OracleID      string `json:"oracle_id"`
	MultiverseIDs []int  `json:"multiverse_ids"`
	MtgoID        int    `json:"mtgo_id"`
	MtgoFoilID    int    `json:"mtgo_foil_id"`
	TcgplayerID   int    `json:"tcgplayer_id"`
	CardmarketID  int    `json:"cardmarket_id"`
	Name          string `json:"name"`
	Lang          string `json:"lang"`
	ReleasedAt    string `json:"released_at"`
	Uri           string `json:"uri"`
	ScryfallUri   string `json:"scryfall_uri"`
	Layout        string `json:"layout"`
	HighresImage  bool   `json:"highres_image"`
	ImageStatus   string `json:"image_status"`
	ImageUris     struct {
		Small      string `json:"small"`
		Normal     string `json:"normal"`
		Large      string `json:"large"`
		Png        string `json:"png"`
		ArtCrop    string `json:"art_crop"`
		BorderCrop string `json:"border_crop"`
	} `json:"image_uris"`
	ManaCost      string   `json:"mana_cost"`
	Cmc           float64  `json:"cmc"`
	TypeLine      string   `json:"type_line"`
	OracleText    string   `json:"oracle_text"`
	Colors        []string `json:"colors"`
	ColorIdentity []string `json:"color_identity"`
	Keywords      []string `json:"keywords"`
	Legalities    struct {
		Standard        string `json:"standard"`
		Future          string `json:"future"`
		Historic        string `json:"historic"`
		Timeless        string `json:"timeless"`
		Gladiator       string `json:"gladiator"`
		Pioneer         string `json:"pioneer"`
		Modern          string `json:"modern"`
		Legacy          string `json:"legacy"`
		Pauper          string `json:"pauper"`
		Vintage         string `json:"vintage"`
		Penny           string `json:"penny"`
		Commander       string `json:"commander"`
		Oathbreaker     string `json:"oathbreaker"`
		StandardBrawl   string `json:"standardbrawl"`
		Brawl           string `json:"brawl"`
		Alchemy         string `json:"alchemy"`
		PauperCommander string `json:"paupercommander"`
		Duel            string `json:"duel"`
		Oldschool       string `json:"oldschool"`
		Premodern       string `json:"premodern"`
		Predh           string `json:"predh"`
	} `json:"legalities"`
	Games           []string `json:"games"`
	Reserved        bool     `json:"reserved"`
	GameChanger     bool     `json:"game_changer"`
	Foil            bool     `json:"foil"`
	Nonfoil         bool     `json:"nonfoil"`
	Finishes        []string `json:"finishes"`
	Oversized       bool     `json:"oversized"`
	Promo           bool     `json:"promo"`
	Reprint         bool     `json:"reprint"`
	Variation       bool     `json:"variation"`
	SetID           string   `json:"set_id"`
	Set             string   `json:"set"`
	SetName         string   `json:"set_name"`
	SetType         string   `json:"set_type"`
	SetUri          string   `json:"set_uri"`
	SetSearchUri    string   `json:"set_search_uri"`
	ScryfallSetUri  string   `json:"scryfall_set_uri"`
	RulingsUri      string   `json:"rulings_uri"`
	PrintsSearchUri string   `json:"prints_search_uri"`
	CollectorNumber string   `json:"collector_number"`
	Digital         bool     `json:"digital"`
	Rarity          string   `json:"rarity"`
	FlavorText      string   `json:"flavor_text"`
	CardBackID      string   `json:"card_back_id"`
	Artist          string   `json:"artist"`
	ArtistIDs       []string `json:"artist_ids"`
	IllustrationID  string   `json:"illustration_id"`
	BorderColor     string   `json:"border_color"`
	Frame           string   `json:"frame"`
	FullArt         bool     `json:"full_art"`
	Textless        bool     `json:"textless"`
	Booster         bool     `json:"booster"`
	StorySpotlight  bool     `json:"story_spotlight"`
	EdhrecRank      int      `json:"edhrec_rank"`
	PennyRank       int      `json:"penny_rank"`
	Prices          struct {
		Usd       string `json:"usd"`
		UsdFoil   string `json:"usd_foil"`
		UsdEtched string `json:"usd_etched"`
		Eur       string `json:"eur"`
		EurFoil   string `json:"eur_foil"`
		Tix       string `json:"tix"`
	} `json:"prices"`
	RelatedUris struct {
		Gatherer                  string `json:"gatherer"`
		TcgplayerInfiniteArticles string `json:"tcgplayer_infinite_articles"`
		TcgplayerInfiniteDecks    string `json:"tcgplayer_infinite_decks"`
		Edhrec                    string `json:"edhrec"`
	} `json:"related_uris"`
	PurchaseUris struct {
		Tcgplayer   string `json:"tcgplayer"`
		Cardmarket  string `json:"cardmarket"`
		Cardhoarder string `json:"cardhoarder"`
	} `json:"purchase_uris"`
}

type ScryCards struct {
	Cards   []ScryCard `json:"data"`
	HasMore bool       `json:"has_more"`
	Total   int        `json:"total_cards"`
	Object  string     `json:"object"`
}

type Card struct {
	Object        string `json:"object"`
	ID            string `json:"id"`
	OracleID      string `json:"oracle_id"`
	MultiverseIDs string `json:"multiverse_ids"`
	MtgoID        int    `json:"mtgo_id"`
	MtgoFoilID    int    `json:"mtgo_foil_id"`
	TcgplayerID   int    `json:"tcgplayer_id"`
	CardmarketID  int    `json:"cardmarket_id"`
	Name          string `json:"name"`
	Lang          string `json:"lang"`
	ReleasedAt    string `json:"released_at"`
	Uri           string `json:"uri"`
	ScryfallUri   string `json:"scryfall_uri"`
	Layout        string `json:"layout"`
	HighresImage  bool   `json:"highres_image"`
	ImageStatus   string `json:"image_status"`
	ImageUris     struct {
		Small      string `json:"small"`
		Normal     string `json:"normal"`
		Large      string `json:"large"`
		Png        string `json:"png"`
		ArtCrop    string `json:"art_crop"`
		BorderCrop string `json:"border_crop"`
	} `json:"image_uris"`
	ManaCost      string  `json:"mana_cost"`
	Cmc           float64 `json:"cmc"`
	TypeLine      string  `json:"type_line"`
	OracleText    string  `json:"oracle_text"`
	Colors        string  `json:"colors"`
	ColorIdentity string  `json:"color_identity"`
	Keywords      string  `json:"keywords"`
	Legalities    struct {
		Standard        string `json:"standard"`
		Future          string `json:"future"`
		Historic        string `json:"historic"`
		Timeless        string `json:"timeless"`
		Gladiator       string `json:"gladiator"`
		Pioneer         string `json:"pioneer"`
		Modern          string `json:"modern"`
		Legacy          string `json:"legacy"`
		Pauper          string `json:"pauper"`
		Vintage         string `json:"vintage"`
		Penny           string `json:"penny"`
		Commander       string `json:"commander"`
		Oathbreaker     string `json:"oathbreaker"`
		StandardBrawl   string `json:"standardbrawl"`
		Brawl           string `json:"brawl"`
		Alchemy         string `json:"alchemy"`
		PauperCommander string `json:"paupercommander"`
		Duel            string `json:"duel"`
		Oldschool       string `json:"oldschool"`
		Premodern       string `json:"premodern"`
		Predh           string `json:"predh"`
	} `json:"legalities"`
	Games           string `json:"games"`
	Reserved        bool   `json:"reserved"`
	GameChanger     bool   `json:"game_changer"`
	Foil            bool   `json:"foil"`
	Nonfoil         bool   `json:"nonfoil"`
	Finishes        string `json:"finishes"`
	Oversized       bool   `json:"oversized"`
	Promo           bool   `json:"promo"`
	Reprint         bool   `json:"reprint"`
	Variation       bool   `json:"variation"`
	SetID           string `json:"set_id"`
	Set             string `json:"set"`
	SetName         string `json:"set_name"`
	SetType         string `json:"set_type"`
	SetUri          string `json:"set_uri"`
	SetSearchUri    string `json:"set_search_uri"`
	ScryfallSetUri  string `json:"scryfall_set_uri"`
	RulingsUri      string `json:"rulings_uri"`
	PrintsSearchUri string `json:"prints_search_uri"`
	CollectorNumber string `json:"collector_number"`
	Digital         bool   `json:"digital"`
	Rarity          string `json:"rarity"`
	FlavorText      string `json:"flavor_text"`
	CardBackID      string `json:"card_back_id"`
	Artist          string `json:"artist"`
	ArtistIDs       string `json:"artist_ids"`
	IllustrationID  string `json:"illustration_id"`
	BorderColor     string `json:"border_color"`
	Frame           string `json:"frame"`
	FullArt         bool   `json:"full_art"`
	Textless        bool   `json:"textless"`
	Booster         bool   `json:"booster"`
	StorySpotlight  bool   `json:"story_spotlight"`
	EdhrecRank      int    `json:"edhrec_rank"`
	PennyRank       int    `json:"penny_rank"`
	Prices          struct {
		Usd       string `json:"usd"`
		UsdFoil   string `json:"usd_foil"`
		UsdEtched string `json:"usd_etched"`
		Eur       string `json:"eur"`
		EurFoil   string `json:"eur_foil"`
		Tix       string `json:"tix"`
	} `json:"prices"`
	RelatedUris struct {
		Gatherer                  string `json:"gatherer"`
		TcgplayerInfiniteArticles string `json:"tcgplayer_infinite_articles"`
		TcgplayerInfiniteDecks    string `json:"tcgplayer_infinite_decks"`
		Edhrec                    string `json:"edhrec"`
	} `json:"related_uris"`
	PurchaseUris struct {
		Tcgplayer   string `json:"tcgplayer"`
		Cardmarket  string `json:"cardmarket"`
		Cardhoarder string `json:"cardhoarder"`
	} `json:"purchase_uris"`
}
